<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderFlow.Domain\OrderFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\*.sql" />
  </ItemGroup>

</Project>
